language: node_js
node_js:
- '12'
addons:
  sonarcloud:
    organization: "magalierambla"

branches:
  only:
  - master

install:
- npm install
- npm i -g angular-cli
before_script:
- npm test
script:
- echo 'ok'


cache:
  directories:
  - node_modules